name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: stakater/.github/.github/workflows/release_template.yaml@v0.0.112
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
